/**
 * DB가 비어있을 때 디자인 시연을 위한 폴백 데이터.
 * TÀMH 실제 메뉴 중 일부를 발췌.
 */
import type { Category, Menu } from "@/types/database";

const now = new Date().toISOString();

export const FALLBACK_CATEGORIES: Category[] = [
  {
    id: "cat-signature",
    name: "Signature",
    subtitle: "This Week's Curated Picks",
    priority: 0,
    icon: "Sparkles",
    created_at: now,
  },
  {
    id: "cat-highland",
    name: "Highland",
    subtitle: "Single Malt · Scotland Highland",
    priority: 10,
    icon: "Mountain",
    created_at: now,
  },
  {
    id: "cat-speyside",
    name: "Speyside",
    subtitle: "Single Malt · Speyside Region",
    priority: 20,
    icon: "Trees",
    created_at: now,
  },
  {
    id: "cat-islay",
    name: "Islay",
    subtitle: "Single Malt · The Isle of Peat",
    priority: 30,
    icon: "Waves",
    created_at: now,
  },
  {
    id: "cat-japan",
    name: "Japan",
    subtitle: "Japanese Whisky",
    priority: 40,
    icon: "Cherry",
    created_at: now,
  },
];

export const FALLBACK_MENUS: Menu[] = [
  // SIGNATURE
  {
    id: "m-signature-1",
    category_id: "cat-signature",
    name: "Royal Salute 21y",
    name_ko: "로얄살루트 21년 (이번 주 할인)",
    description:
      "21년의 깊이를 잔에 담은 한 잔. 셰리와 버번 캐스크가 우아하게 어우러진 균형 잡힌 블렌드.",
    price: 25000,
    bottle_price: 640000,
    image_url: null,
    is_active: true,
    is_recommended: true,
    origin: "Scotland · Blended",
    abv: 40,
    cask_type: "Sherry / Bourbon",
    created_at: now,
    updated_at: now,
  },
  {
    id: "m-signature-2",
    category_id: "cat-signature",
    name: "Glenfiddich 23y",
    name_ko: "글렌피딕 23년 (이번 주 할인)",
    description:
      "23년의 시간을 머금은 셰리 캐스크의 깊은 다크 프룻과 우디 노트.",
    price: 60000,
    bottle_price: 1350000,
    image_url: null,
    is_active: true,
    is_recommended: true,
    origin: "Speyside",
    abv: 43,
    cask_type: "Sherry Cask",
    created_at: now,
    updated_at: now,
  },
  // HIGHLAND
  {
    id: "m-hl-1",
    category_id: "cat-highland",
    name: "Dalmore 12y",
    name_ko: "달모어 12년",
    description:
      "셰리 캐스크 피니쉬가 만들어내는 오렌지 마멀레이드와 초콜릿의 향연.",
    price: 18000,
    bottle_price: 300000,
    image_url: null,
    is_active: true,
    is_recommended: false,
    origin: "Highland",
    abv: 40,
    cask_type: "Sherry / Bourbon",
    created_at: now,
    updated_at: now,
  },
  {
    id: "m-hl-2",
    category_id: "cat-highland",
    name: "Glendronach 12y",
    name_ko: "글렌드로낙 12년",
    description: "PX와 올로로소 셰리의 진한 풍미. 따뜻한 겨울밤에 어울리는 한 잔.",
    price: 19000,
    bottle_price: 290000,
    image_url: null,
    is_active: true,
    is_recommended: true,
    origin: "Highland",
    abv: 43,
    cask_type: "PX / Oloroso",
    created_at: now,
    updated_at: now,
  },
  // SPEYSIDE
  {
    id: "m-sp-1",
    category_id: "cat-speyside",
    name: "Macallan 18y Sherry",
    name_ko: "맥켈란 셰리 캐스크 18년",
    description:
      "18년 셰리 오크 숙성의 정수. 풍부한 다크 프룻과 스파이스의 완벽한 균형.",
    price: 60000,
    bottle_price: 1200000,
    image_url: null,
    is_active: true,
    is_recommended: true,
    origin: "Speyside",
    abv: 43,
    cask_type: "Sherry Cask",
    created_at: now,
    updated_at: now,
  },
  {
    id: "m-sp-2",
    category_id: "cat-speyside",
    name: "Balvenie DoubleWood 12y",
    name_ko: "발베니 더블우드 12년",
    description: "버번 + 셰리 캐스크의 더블 매튜링. 꿀과 바닐라의 부드러운 한 잔.",
    price: 18000,
    bottle_price: 320000,
    image_url: null,
    is_active: true,
    is_recommended: false,
    origin: "Speyside",
    abv: 40,
    cask_type: "Bourbon / Sherry",
    created_at: now,
    updated_at: now,
  },
  // ISLAY
  {
    id: "m-is-1",
    category_id: "cat-islay",
    name: "Ardbeg 10y",
    name_ko: "아드벡 10년",
    description: "강렬한 피트와 바닷바람. 아일라의 정체성을 담은 한 잔.",
    price: 18000,
    bottle_price: 290000,
    image_url: null,
    is_active: true,
    is_recommended: true,
    origin: "Islay",
    abv: 46,
    cask_type: "Ex-Bourbon",
    created_at: now,
    updated_at: now,
  },
  {
    id: "m-is-2",
    category_id: "cat-islay",
    name: "Lagavulin 16y",
    name_ko: "라가불린 16년",
    description: "긴 숙성이 다듬어낸 부드러운 스모키. 클래식한 한 모금.",
    price: 24000,
    bottle_price: 400000,
    image_url: null,
    is_active: true,
    is_recommended: false,
    origin: "Islay",
    abv: 43,
    cask_type: "Ex-Bourbon",
    created_at: now,
    updated_at: now,
  },
  // JAPAN
  {
    id: "m-jp-1",
    category_id: "cat-japan",
    name: "Hibiki Harmony",
    name_ko: "히비키 하모니",
    description: "다섯 가지 캐스크가 만들어낸 우아한 조화. 일본 블렌딩의 진수.",
    price: 29000,
    bottle_price: 540000,
    image_url: null,
    is_active: true,
    is_recommended: false,
    origin: "Japan",
    abv: 43,
    cask_type: "Blended",
    created_at: now,
    updated_at: now,
  },
  {
    id: "m-jp-2",
    category_id: "cat-japan",
    name: "Yamazaki 12y",
    name_ko: "산토리 야마자키 12년",
    description: "미즈나라 캐스크의 영향이 더해진 향긋하고 섬세한 한 잔.",
    price: 39000,
    bottle_price: 790000,
    image_url: null,
    is_active: true,
    is_recommended: true,
    origin: "Japan",
    abv: 43,
    cask_type: "Mizunara",
    created_at: now,
    updated_at: now,
  },
];
